@extends('layouts.app')

@section('title', 'Trainees Report')

@section('content')
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 pb-4 border-b border-border-dark/50 print:hidden">
        <h2 class="text-3xl font-bold text-gray-100 mb-4 md:mb-0">Trainees Report Overview</h2>
        
        <button onclick="window.print()" class="px-5 py-2 bg-accent-purple/90 hover:bg-accent-purple text-white font-semibold rounded-lg transition-all duration-200 shadow-md flex items-center print-button">
            <svg class="w-5 h-5 inline-block mr-2 -mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m0 0v-6a2 2 0 012-2h4a2 2 0 012 2v6m-4-2a2 2 0 01-2-2h-4a2 2 0 01-2-2v-4a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2h-4a2 2 0 01-2-2z"></path></svg>
            Print Report
        </button>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 text-center print:hidden">
        <div class="p-4 bg-primary-dark/50 rounded-lg border border-border-dark">
            <p class="text-sm text-gray-400 font-medium">Report Generated</p>
            <p class="text-xl font-bold text-white">{{ date('d-m-Y') }}</p>
            <p class="text-xs text-gray-500">{{ date('H:i:s') }}</p>
        </div>
        <div class="p-4 bg-primary-dark/50 rounded-lg border border-border-dark">
            <p class="text-sm text-gray-400 font-medium">Total Trainees</p>
            <p class="text-3xl font-bold text-accent-orange">{{ $trainees->count() }}</p>
        </div>
        <div class="p-4 bg-primary-dark/50 rounded-lg border border-border-dark">
            <p class="text-sm text-gray-400 font-medium">Generated By</p>
            <p class="text-xl font-bold text-white">{{ Auth::user()->full_name }}</p>
        </div>
    </div>
    
    <div class="print-only" style="display: none;">
        <h1 style="font-size: 20px; font-weight: bold; margin-bottom: 10px; text-align: center;">SJITC Trainees Official Report</h1>
        <p style="font-size: 12px; margin-bottom: 20px;"><strong>Report Generated:</strong> {{ date('d-m-Y H:i:s') }}</p>
        <p style="font-size: 12px; margin-bottom: 10px;"><strong>Total Trainees:</strong> {{ $trainees->count() }}</p>
        <p style="font-size: 12px; margin-bottom: 20px;"><strong>Generated By:</strong> {{ Auth::user()->full_name }}</p>
    </div>

    <div class="overflow-x-auto">
        <table class="min-w-full divide-y divide-border-dark border border-border-dark print-table">
            <thead>
                <tr class="text-left text-xs font-semibold uppercase tracking-wider text-gray-400 bg-card-dark/70">
                    <th class="px-4 py-3">ID</th>
                    <th class="px-4 py-3">Full Name</th>
                    <th class="px-4 py-3">Gender</th>
                    <th class="px-4 py-3">DOB</th>
                    <th class="px-4 py-3">Age</th>
                    <th class="px-4 py-3">Trade</th>
                    <th class="px-4 py-3">Level</th>
                    <th class="px-4 py-3">Parent Name</th>
                    <th class="px-4 py-3">Parent Phone</th>
                    <th class="px-4 py-3">District</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-border-dark/50">
                @forelse($trainees as $trainee)
                <tr class="hover:bg-card-dark/70 transition duration-100 text-gray-200">
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ $trainee->traineeId }}</td>
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ $trainee->tFirstName }} {{ $trainee->tLastName }}</td>
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ $trainee->tGender }}</td>
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ date('d-m-Y', strtotime($trainee->DOB)) }}</td>
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ date('Y') - date('Y', strtotime($trainee->DOB)) }}</td>
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ $trainee->trade->TradeName ?? 'N/A' }}</td>
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ $trainee->Level }}</td>
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ $trainee->parent->pFirstName ?? 'N/A' }} {{ $trainee->parent->pLastName ?? '' }}</td>
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ $trainee->parent->PhoneNumber ?? 'N/A' }}</td>
                    <td class="px-4 py-3 whitespace-nowrap text-sm">{{ $trainee->parent->District ?? 'N/A' }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="10" class="px-4 py-8 text-center text-gray-500 italic">
                        No trainees registered yet to generate a report.
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <style>
    @media print {
        .print\:hidden,
        .print-button,
        .navbar,
        .sidebar,
        nav,
        header,
        footer,
        button {
            display: none !important;
        }

        body {
            background: white !important;
            color: black !important;
            margin: 0 !important;
            padding: 0 !important;
        }

        * {
            background: white !important;
            color: black !important;
            box-shadow: none !important;
            border-radius: 0 !important;
        }


        .card,
        [class*="container"],
        [class*="card"] {
            margin: 0 auto !important;
            padding: 20px !important;
            max-width: 100% !important;
            width: 100% !important;
        }

        .print-only {
            display: block !important;
        }


        .print-table,
        table {
            width: 100% !important;
            border-collapse: collapse !important;
            margin: 0 auto !important;
            background: white !important;
            font-size: 9pt !important;
        }

        .print-table th,
        .print-table td,
        table th,
        table td {
            border: 1px solid #000 !important;
            padding: 6px 8px !important;
            text-align: left !important;
            color: black !important;
            background: white !important;
            white-space: normal !important;
            font-size: 9pt !important;
        }

        .print-table th,
        table th {
            background: #f0f0f0 !important;
            font-weight: bold !important;
            text-transform: none !important;
        }

        [class*="bg-"],
        [class*="text-"],
        [class*="border-"],
        [class*="rounded"],
        [class*="shadow"],
        [class*="hover:"],
        [class*="transition"],
        [class*="divide-"],
        [class*="tracking-"],
        [class*="uppercase"] {
            background: white !important;
            color: black !important;
            border-color: #000 !important;
            border-radius: 0 !important;
            box-shadow: none !important;
            text-transform: none !important;
            letter-spacing: normal !important;
        }

        @page {
            margin: 0.5in;
            size: A4 landscape;
        }
    }
    </style>
@endsection